### ISSUE TITLE
1.16.5 Can't open cmdconfig

### ISSUE THREAD

**Issue by andriiqx** [CreativeMD/OpticManager#18]
Also, i can join my server even without optic manager, it's okay?

When i'm typing /cmdconfig on server i see that:  org.bukkit.command.CommandException: Unhandled exception executing 'cmdconfig' in org.bukkit.craftbukkit.v1_16_R3.command.VanillaCommandWrapper(cmdconfig)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:163) ~[forge:?]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:680) ~[forge:1.16.5-98eabb0e]
        at net.minecraft.network.play.ServerPlayNetHandler.func_147361_d(ServerPlayNetHandler.java:1796) ~[?:?]
        at net.minecraft.network.play.ServerPlayNetHandler.func_244548_c(ServerPlayNetHandler.java:1649) ~[?:?]
        at net.minecraft.network.play.ServerPlayNetHandler.func_147354_a(ServerPlayNetHandler.java:1603) ~[?:?]
        at net.minecraft.network.play.client.CChatMessagePacket.func_148833_a(CChatMessagePacket.java:38) ~[?:?]
        at net.minecraft.network.play.client.CChatMessagePacket.func_148833_a(CChatMessagePacket.java:8) ~[?:?]
        at net.minecraft.network.PacketThreadUtil.func_225383_a(PacketThreadUtil.java:22) ~[?:?]
        at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?]
        at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:885) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:169) ~[?:?]
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:868) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:862) ~[?:?]
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:848) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:779) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:265) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class team.creative.creativecore.common.gui.style.GuiStyle
        at team.creative.creativecore.common.gui.GuiLayer.<init>(GuiLayer.java:16) ~[?:?]
        at team.creative.creativecore.common.config.gui.ConfigGuiLayer.<init>(ConfigGuiLayer.java:42) ~[?:?]
        at team.creative.creativecore.CreativeCore$2.create(CreativeCore.java:74) ~[?:?]
        at team.creative.creativecore.common.gui.handler.GuiContainerHandler.lambda$registerGuiHandler$1(GuiContainerHandler.java:52) ~[?:?]
        at net.minecraft.inventory.container.SimpleNamedContainerProvider.createMenu(SourceFile:25) ~[?:?]
        at net.minecraft.entity.player.ServerPlayerEntity.func_213829_a(ServerPlayerEntity.java:1188) ~[?:?]
        at team.creative.creativecore.common.gui.handler.GuiContainerHandler.openGui(GuiContainerHandler.java:67) ~[?:?]
        at team.creative.creativecore.CreativeCore.lambda$server$5(CreativeCore.java:88) ~[?:?]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:262) ~[?:?]
        at net.minecraft.command.Commands.func_197059_a(Commands.java:266) ~[?:?]
        at net.minecraft.command.Commands.handleCommand(Commands.java:321) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.command.VanillaCommandWrapper.execute(VanillaCommandWrapper.java:44) ~[forge:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:156) ~[forge:?]
        ... 20 more
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.RuntimeException: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER [in thread "Server thread"]
        at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:73) ~[server.jar:36.2]
        at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) ~[modlauncher-8.1.3.jar:?]
        at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-8.1.3.jar:?]
        at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) ~[modlauncher-8.1.3.jar:?]
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.1.3.jar:?]
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.1.3.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at team.creative.creativecore.common.gui.style.GuiStyle.<clinit>(GuiStyle.java:28) ~[?:?]
        at team.creative.creativecore.common.gui.GuiLayer.<init>(GuiLayer.java:16) ~[?:?]
        at team.creative.creativecore.common.config.gui.ConfigGuiLayer.<init>(ConfigGuiLayer.java:42) ~[?:?]
        at team.creative.creativecore.CreativeCore$2.create(CreativeCore.java:74) ~[?:?]
        at team.creative.creativecore.common.gui.handler.GuiContainerHandler.lambda$registerGuiHandler$1(GuiContainerHandler.java:52) ~[?:?]
        at net.minecraft.inventory.container.SimpleNamedContainerProvider.createMenu(SourceFile:25) ~[?:?]
        at net.minecraft.entity.player.ServerPlayerEntity.func_213829_a(ServerPlayerEntity.java:1188) ~[?:?]
        at team.creative.creativecore.common.gui.handler.GuiContainerHandler.openGui(GuiContainerHandler.java:67) ~[?:?]
        at team.creative.creativecore.CreativeCore.lambda$server$5(CreativeCore.java:88) ~[?:?]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:262) ~[?:?]
        at net.minecraft.command.Commands.func_197059_a(Commands.java:266) ~[?:?]
        at net.minecraft.command.Commands.handleCommand(Commands.java:321) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.command.VanillaCommandWrapper.execute(VanillaCommandWrapper.java:44) ~[forge:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:156) ~[forge:?]
        ... 20 more

**Comment by andriiqx** [comment]
Oh. sorry, i'm just typed command in singleplayer and it's alright

**Comment by andriiqx** [comment]
But everytime i launch server, the config being overwritten

**Comment by CreativeMD** [comment]
This has been discussed on discord. That's why I will close this issue here.
