### ISSUE TITLE
NoClassDefFoundError: com/creativemd/igcm/api/ConfigElement

### ISSUE THREAD

**Issue by TomberWolf** [CreativeMD/OpticManager#2]
```
WARNING: coremods are present:
  CreativePatchingLoader (CC-CreativeCore v1.6.26 mc1.10.2.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.5.7.241-universal.jar)
  FarseekCoreMod (Farseek-1.9.4-2.1.jar)
  IceAndFireForgeLoading (iceandfire-1.0.jar)
  FMLPlugin (InventoryTweaks-1.62-dev-66.jar)
  NWRTweak (redstonepaste-mc1.9.4-1.7.4.jar)
  LoadingPlugin (HardcoreDarkness-MC1.9.4-1.8.jar)
  AppleCore (AppleCore-mc1.10.2-2.1.2.jar)
  DynamicSurroundingsCore (DynamicSurroundings-1.10.2-3.3.3.1.jar)
  ShetiPhian-ASM (platforms-shetiphiancore-1.10.0-3.3.8.jar)
  BetterFoliageLoader (BetterFoliage-MC1.10.2-2.1.3.jar)
  NEICorePlugin (NotEnoughItems-1.10.2-2.1.3.206-universal.jar)
  TheBetweenlandsLoadingPlugin (TheBetweenlands-2.0.2-alpha-universal.jar)
  LoadingPlugin (Bloodmoon-MC1.10.2-1.5.1.jar)
  SignPictureCorePlugin (SignPicture-1.10.2-2.7.1-universal.jar)
  DummyPlugin (AdChimneys-ForgeEndertech-1.10.2-1.2.1.0-build.0018.jar)
  OpticPatchingLoader (OpticManager v1.1.1 mc1.11.2.jar)
  BookshelfLoadingPlugin (EnchantingPlus-Bookshelf-1.10.2-1.4.4.347.jar)
  llibrary (iceandfire-llibrary-1.7.4-1.10.2.jar)
  ChiselCorePlugin (Chisel-MC1.10.2-0.0.9.15.jar)
  ArsMagica2-Preloader (ArsMagica2-1.10.2-1.5.0-18.jar)
  TANLoadingPlugin (ToughAsNails-1.9.4-1.1.1.jar)
Contact their authors BEFORE contacting forge

// My bad.

Time: 4/5/17 1:59 AM
Description: Initializing game

java.lang.NoClassDefFoundError: com/creativemd/igcm/api/ConfigElement
	at com.creativemd.opticmanager.OpticManager.init(OpticManager.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:805)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:334)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: com.creativemd.igcm.api.ConfigElement
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 33 more
Caused by: java.lang.NullPointerException


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.creativemd.opticmanager.OpticManager.init(OpticManager.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:805)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:334)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by CreativeMD** [comment]
You have to install InGameConfigManager (IGCM) as well.

**Comment by TomberWolf** [comment]
It is
IGCM alpha v1.0.6 mc1.10.zip

**Comment by CreativeMD** [comment]
You have installed OpticManager v1.1.1 for 1.11.2, but you are using 1.10.2. You can download the 1.10.2 version of OpticManager here: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2559807-opticmanager-v1-1-1-synchronized-client-settings

**Comment by TomberWolf** [comment]
Damn, sorry, than it was the wrong crash report.
I tried the newer version after the 1.10 crash.


```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CreativePatchingLoader (CC-CreativeCore v1.6.26 mc1.10.2.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.5.7.241-universal.jar)
  FarseekCoreMod (Farseek-1.9.4-2.1.jar)
  IceAndFireForgeLoading (iceandfire-1.0.jar)
  FMLPlugin (InventoryTweaks-1.62-dev-66.jar)
  NWRTweak (redstonepaste-mc1.9.4-1.7.4.jar)
  LoadingPlugin (HardcoreDarkness-MC1.9.4-1.8.jar)
  AppleCore (AppleCore-mc1.10.2-2.1.2.jar)
  DynamicSurroundingsCore (DynamicSurroundings-1.10.2-3.3.3.1.jar)
  ShetiPhian-ASM (platforms-shetiphiancore-1.10.0-3.3.8.jar)
  BetterFoliageLoader (BetterFoliage-MC1.10.2-2.1.3.jar)
  NEICorePlugin (NotEnoughItems-1.10.2-2.1.3.206-universal.jar)
  TheBetweenlandsLoadingPlugin (TheBetweenlands-2.0.2-alpha-universal.jar)
  LoadingPlugin (Bloodmoon-MC1.10.2-1.5.1.jar)
  OpticPatchingLoader (CC-OpticManager v1.1.1 mc1.10.2.jar)
  SignPictureCorePlugin (SignPicture-1.10.2-2.7.1-universal.jar)
  DummyPlugin (AdChimneys-ForgeEndertech-1.10.2-1.2.1.0-build.0018.jar)
  BookshelfLoadingPlugin (EnchantingPlus-Bookshelf-1.10.2-1.4.4.347.jar)
  llibrary (iceandfire-llibrary-1.7.4-1.10.2.jar)
  ChiselCorePlugin (Chisel-MC1.10.2-0.0.9.15.jar)
  ArsMagica2-Preloader (ArsMagica2-1.10.2-1.5.0-18.jar)
  TANLoadingPlugin (ToughAsNails-1.9.4-1.1.1.jar)
Contact their authors BEFORE contacting forge

// On the bright side, I bought you a teddy bear!

Time: 05.04.17 01:56
Description: Initializing game

java.lang.NoClassDefFoundError: com/creativemd/igcm/api/common/branch/ConfigBranch
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at net.minecraftforge.fml.common.Loader.identifyMods(Loader.java:368)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:531)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:220)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:439)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: com.creativemd.igcm.api.common.branch.ConfigBranch
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 14 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 16 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at net.minecraftforge.fml.common.Loader.identifyMods(Loader.java:368)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:531)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:220)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:439)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_121, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 7375661600 bytes (7033 MB) / 8267825152 bytes (7884 MB) up to 8267825152 bytes (7884 MB)
	JVM Flags: 25 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G -Xms8G -Xmn3072m -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+UseNUMA -XX:+CMSParallelRemarkEnabled -XX:MaxGCPauseMillis=30 -XX:GCPauseIntervalMillis=150 -XX:+UseAdaptiveGCBoundary -XX:-UseGCOverheadLimit -XX:+UseBiasedLocking -XX:SurvivorRatio=8 -XX:TargetSurvivorRatio=90 -XX:MaxTenuringThreshold=15 -XX:+UseFastAccessorMethods -XX:+UseCompressedOops -XX:+OptimizeStringConcat -XX:+AggressiveOpts -XX:ReservedCodeCacheSize=2048m -XX:+UseCodeCacheFlushing -XX:SoftRefLRUPolicyMSPerMB=20000 -XX:ParallelGCThreads=10
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.3.2254 Optifine OptiFine_1.10.2_HD_U_D7 4 mods loaded, 0 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
		mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
		FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2254.jar) 
		Forge{12.18.3.2254} [Minecraft Forge] (forge-1.10.2-12.18.3.2254.jar) 
		creativecoredummy{1.0.0} [CreativeCoreDummy] (minecraft.jar) 
	Loaded coremods (and transformers): 
CreativePatchingLoader (CC-CreativeCore v1.6.26 mc1.10.2.jar)
  
CCLCorePlugin (CodeChickenLib-1.10.2-2.5.7.241-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.CCL_ASMTransformer
FarseekCoreMod (Farseek-1.9.4-2.1.jar)
  farseek.core.FarseekClassTransformer
IceAndFireForgeLoading (iceandfire-1.0.jar)
  com.github.alexthe666.iceandfire.access.IceAndFireTransformer
FMLPlugin (InventoryTweaks-1.62-dev-66.jar)
  invtweaks.forge.asm.ContainerTransformer
NWRTweak (redstonepaste-mc1.9.4-1.7.4.jar)
  net.fybertech.nwr.NWRTransformer
LoadingPlugin (HardcoreDarkness-MC1.9.4-1.8.jar)
  lumien.hardcoredarkness.asm.ClassTransformer
AppleCore (AppleCore-mc1.10.2-2.1.2.jar)
  squeek.applecore.asm.TransformerModuleHandler
DynamicSurroundingsCore (DynamicSurroundings-1.10.2-3.3.3.1.jar)
  org.blockartistry.mod.DynSurround.asm.Transformer
ShetiPhian-ASM (platforms-shetiphiancore-1.10.0-3.3.8.jar)
  shetiphian.core.asm.ClassTransformer
BetterFoliageLoader (BetterFoliage-MC1.10.2-2.1.3.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
NEICorePlugin (NotEnoughItems-1.10.2-2.1.3.206-universal.jar)
  codechicken.nei.asm.NEITransformer
TheBetweenlandsLoadingPlugin (TheBetweenlands-2.0.2-alpha-universal.jar)
  thebetweenlands.core.TheBetweenlandsClassTransformer
LoadingPlugin (Bloodmoon-MC1.10.2-1.5.1.jar)
  lumien.bloodmoon.asm.ClassTransformer
OpticPatchingLoader (CC-OpticManager v1.1.1 mc1.10.2.jar)
  com.creativemd.opticmanager.OpticTransformer
SignPictureCorePlugin (SignPicture-1.10.2-2.7.1-universal.jar)
  com.kamesuta.mc.signpic.asm.SignPictureTransformer
DummyPlugin (AdChimneys-ForgeEndertech-1.10.2-1.2.1.0-build.0018.jar)
  
BookshelfLoadingPlugin (EnchantingPlus-Bookshelf-1.10.2-1.4.4.347.jar)
  net.darkhax.bookshelf.asm.BookshelfTransformerManager
llibrary (iceandfire-llibrary-1.7.4-1.10.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
ChiselCorePlugin (Chisel-MC1.10.2-0.0.9.15.jar)
  team.chisel.common.asm.ChiselTransformer
ArsMagica2-Preloader (ArsMagica2-1.10.2-1.5.0-18.jar)
  am2.asm.Transformer
TANLoadingPlugin (ToughAsNails-1.9.4-1.1.1.jar)
  toughasnails.asm.transformer.BlockCropsTransformer
  toughasnails.asm.transformer.EntityRendererTransformer
  toughasnails.asm.transformer.WorldTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 378.78' Renderer: 'GeForce GTX 1080 Ti/PCIe/SSE2'
	Launched Version: 1.10.2-forge1.10.2-12.18.3.2254
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1080 Ti/PCIe/SSE2 GL version 4.5.0 NVIDIA 378.78, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.
```

**Comment by CreativeMD** [comment]
Does this version fix it?
https://www.dropbox.com/s/x8r2wv316l0ukv3/OpticManager%20v1.1.2%20mc1.10.2.jar?dl=1

**Comment by TomberWolf** [comment]
I will take a look at it when I'm home.

**Comment by TomberWolf** [comment]
Seems to work!

**Comment by CreativeMD** [comment]
Good to hear that, uploaded it. Thanks for reporting this issue.

**Comment by TomberWolf** [comment]
I have another issue with IGCM.
You may want to take a look at it :-)

https://github.com/CreativeMD/IGCM/issues/19
