### ISSUE TITLE
1.12.2 crashing

### ISSUE THREAD

**Issue by Thyriel** [CreativeMD/OpticManager#5]
[00:18:49] [main/DEBUG] [FML/]: Coremod plugin class FMLForgePlugin run successfully
[00:18:49] [main/INFO] [LaunchWrapper/]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[00:18:49] [main/DEBUG] [FML/]: Injecting coremod OpticPatchingLoader \{com.creativemd.opticmanager.OpticPatchingLoader\} class transformers
[00:18:49] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.NoClassDefFoundError: com/creativemd/opticmanager/OpticTransformer
[00:18:49] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at com.creativemd.opticmanager.OpticPatchingLoader.getASMTransformerClass(OpticPatchingLoader.java:18)
[00:18:49] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:130)
[00:18:49] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[00:18:49] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[00:18:49] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: Caused by: java.lang.ClassNotFoundException: com.creativemd.opticmanager.OpticTransformer
[00:18:49] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[00:18:49] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[00:18:49] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[00:18:49] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	... 4 more
[00:18:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: Caused by: java.lang.NoClassDefFoundError: com/creativemd/creativecore/transformer/CreativeTransformer
[00:18:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at java.lang.ClassLoader.defineClass1(Native Method)
[00:18:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
[00:18:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[00:18:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
[00:18:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	... 6 more
[00:18:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: Caused by: java.lang.ClassNotFoundException: com.creativemd.creativecore.transformer.CreativeTransformer
[00:18:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
[00:18:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[00:18:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[00:18:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	... 10 more

**Comment by CreativeMD** [comment]
You forgot to install CreativeCore.

**Comment by Thyriel** [comment]
Thanks ;)
You know you could provide depending mods so it doesn't crash when they are missing and forge would tell the user what mod is needed ?

**Comment by CreativeMD** [comment]
Unfortunately it crashes before Forge checks for dependencies :(

**Comment by Thyriel** [comment]
Oh ok ^^
Btw when i use this to increase day length and reduce night length:
- ... is the time between 2 ticks staying the same ? So day gets more ticks and night less ticks, or are the ticks stretched ? (important to balance plant growths)
- ... do clients need the mod or only server ?

**Comment by CreativeMD** [comment]
* OpticManager either stretches are skips worldTime. Meaning the number you specify is the number of ticks. Meanwhile the worldTime is still a number between 0 to 23999.
* Yes you need it on client and server.
